#!/usr/bin/env python3

"""
Script to automate folder & file creation for coding challenges

Example:
  - $ python3 accept-challenge
    Num:  33
    Name: Amazing Fibonacci Sequence #5!
    URL:  http://not-important-in-this-example.com
  - creates `./→33_amazing-fibonacci-sequence-5/main.py`
            `./→33_amazing-fibonacci-sequence-5/tests.py`
"""

import os
import re


UNITTEST_TEMPLATE = """\
import unittest

import main


class SampleTests(unittest.TestCase):

    def test1(self):
        pass # TODO: write unit tests


if __name__ == '__main__':
    unittest.main(verbosity=2)
"""

FUNCTION_TEMPLATE = """\
def foo():
    pass # TODO: implement
"""

REPLACEMENTS = [
    ('test.assert_equals(', 'self.assertEqual(main.')
]


def make_project(num, name, url):
    home = os.environ['HOME']
    os.chdir(home + '/Desktop/')
    name = kebabize(name)
    dirname = f"→{num}_{name}"
    os.makedirs(dirname)
    os.chdir(dirname)
    with open('main.py', 'w') as file:
        file.write(f'"""{url}"""\n\n' + FUNCTION_TEMPLATE)
    with open('tests.py', 'w') as file:
        file.write(UNITTEST_TEMPLATE)


def kebabize(name):
    name = name.strip().lower()
    name = re.sub(r'[^a-z\d\s]+', '', name)  # Remove non-alpha characters
    name = re.sub(r'\s+', '-', name)         # Change whitespaces to dashes
    return name


def main():
    num = input('Num:  ')
    name = input('Name: ')
    url = input('URL:  ')
    make_project(num, name, url)


if __name__ == '__main__':
    main()
